name: khatt_1
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - numpy
  - tensorflow-gpu==1.15.0
  - scipy
  - pip:
    - ds_ctcdecoder
    - mako
    - pandas
    - protobuf
    - pyyaml
    - pyxdg
    - requests
    - tree
